services:
  - type: web
    name: clubconnect
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_NAME
        value: clubconnect
      - key: DB_USER
        value: postgres
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 5432
      - key: SESSION_SECRET
        generateValue: true
      - key: EMAIL_USER
        value: your-email@gmail.com
      - key: EMAIL_PASS
        value: your-app-password 